name: Quality
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace}}/src/github.com/${{ github.repository}}

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Audit
        shell: bash
        run: task verify
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace}}/src/github.com/${{ github.repository}}

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Lint
        shell: bash
        run: task lint
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace}}/src/github.com/${{ github.repository}}

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Test
        run: task test